"""
SwarCare Pipeline - Step 3: Prepare Training & Test Data
=========================================================
PURPOSE:
    Take the healthy segments from Step 2 and organize them into:
    1. Training set (80%) — used to learn "what healthy sounds like"
    2. Testing set (20%) — used to validate detection works
    3. Anomaly test set — generated by corrupting healthy segments

ANOMALY GENERATION:
    Since we don't have real anomaly recordings, we simulate 3 types:
    - DETUNED: Pitch-shift ±2 semitones (string tension issues)
    - BUZZING: Add broadband noise (loose fret / bridge rattle)
    - MUFFLED: Low-pass filter (damping / dead strings)

OUTPUT:
    training_data/
    ├── training/
    │   └── healthy/        ← 80% of segments (for PCA + K-means training)
    ├── testing/
    │   ├── healthy/        ← 20% of segments (should classify as healthy)
    │   └── anomaly/        ← Generated corrupted audio (should classify as anomaly)
    └── synthetic/
        ├── healthy/        ← Artificial veena tones (bonus validation)
        └── anomaly/        ← Corrupted artificial tones

WHY THIS STRUCTURE:
    07_yamnet_transfer.py reads from these exact folders to train and validate.
"""

import os
import sys
import shutil
import numpy as np

try:
    import librosa
    import soundfile as sf
except ImportError:
    print("Missing dependencies. Install with:")
    print("  pip install librosa soundfile numpy")
    sys.exit(1)

# === CONFIGURATION ===
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
SEG_DIR = os.path.join(SCRIPT_DIR, "segments")
OUTPUT_DIR = os.path.join(SCRIPT_DIR, "training_data")

TRAIN_SPLIT = 0.8  # 80% for training
TARGET_SR = 16000
RANDOM_SEED = 42


def generate_detuned(audio, sr):
    """Simulate detuned strings — pitch shift by ±2 semitones."""
    shift = np.random.choice([-2, -1.5, 1.5, 2])
    return librosa.effects.pitch_shift(audio, sr=sr, n_steps=shift)


def generate_buzzing(audio, sr):
    """Simulate buzzing — add broadband noise at 10-30% level."""
    noise_level = np.random.uniform(0.10, 0.30)
    noise = np.random.randn(len(audio)).astype(np.float32) * noise_level
    return audio + noise * np.max(np.abs(audio))


def generate_muffled(audio, sr):
    """Simulate muffled/dead strings — aggressive low-pass filter."""
    # Use librosa's effects or simple spectral roll-off
    # Low-pass at 1000-2000 Hz (veena fundamentals are 100-500Hz, overtones go higher)
    from scipy.signal import butter, sosfilt
    cutoff = np.random.uniform(800, 1500)
    sos = butter(4, cutoff, btype='low', fs=sr, output='sos')
    return sosfilt(sos, audio).astype(np.float32)


def main():
    print("SwarCare Pipeline - Prepare Training Data")
    print("=" * 55)

    # Check segments directory
    if not os.path.exists(SEG_DIR):
        print(f"\n[ERROR] segments/ directory not found: {SEG_DIR}")
        print("Run 02_segment_audio.py first.")
        sys.exit(1)

    # Find all segment WAVs
    seg_files = sorted([f for f in os.listdir(SEG_DIR) if f.endswith('.wav')])
    if not seg_files:
        print(f"\n[ERROR] No WAV files found in: {SEG_DIR}")
        sys.exit(1)

    print(f"\nFound {len(seg_files)} healthy segments in segments/")

    # Shuffle with fixed seed for reproducibility
    np.random.seed(RANDOM_SEED)
    indices = np.random.permutation(len(seg_files))

    # Split into train/test
    split_idx = int(len(seg_files) * TRAIN_SPLIT)
    train_indices = indices[:split_idx]
    test_indices = indices[split_idx:]

    print(f"Split: {len(train_indices)} training / {len(test_indices)} testing")

    # Create output directories
    train_dir = os.path.join(OUTPUT_DIR, "training", "healthy")
    test_healthy_dir = os.path.join(OUTPUT_DIR, "testing", "healthy")
    test_anomaly_dir = os.path.join(OUTPUT_DIR, "testing", "anomaly")

    for d in [train_dir, test_healthy_dir, test_anomaly_dir]:
        os.makedirs(d, exist_ok=True)

    # Copy training segments
    print(f"\n[1/3] Copying {len(train_indices)} training segments...")
    for i in train_indices:
        src = os.path.join(SEG_DIR, seg_files[i])
        dst = os.path.join(train_dir, seg_files[i])
        shutil.copy2(src, dst)

    # Copy test healthy segments
    print(f"[2/3] Copying {len(test_indices)} test (healthy) segments...")
    for i in test_indices:
        src = os.path.join(SEG_DIR, seg_files[i])
        dst = os.path.join(test_healthy_dir, seg_files[i])
        shutil.copy2(src, dst)

    # Generate anomaly segments from test healthy segments
    print(f"[3/3] Generating anomaly segments from test data...")

    anomaly_types = [
        ("detuned", generate_detuned),
        ("buzzing", generate_buzzing),
        ("muffled", generate_muffled),
    ]

    anomaly_count = 0
    for i in test_indices:
        filepath = os.path.join(SEG_DIR, seg_files[i])
        audio, sr = librosa.load(filepath, sr=TARGET_SR, mono=True)

        # Generate one anomaly type per segment (cycle through types)
        atype_name, atype_fn = anomaly_types[anomaly_count % len(anomaly_types)]

        try:
            corrupted = atype_fn(audio, sr)
            out_name = f"{atype_name}_{seg_files[i]}"
            out_path = os.path.join(test_anomaly_dir, out_name)
            sf.write(out_path, corrupted, sr)
            anomaly_count += 1
        except Exception as e:
            print(f"  [WARN] Failed to generate {atype_name} for {seg_files[i]}: {e}")

    # ─── Generate synthetic veena data ───
    print(f"\n[4/4] Generating synthetic veena data...")
    synth_healthy_dir = os.path.join(OUTPUT_DIR, "synthetic", "healthy")
    synth_anomaly_dir = os.path.join(OUTPUT_DIR, "synthetic", "anomaly")
    os.makedirs(synth_healthy_dir, exist_ok=True)
    os.makedirs(synth_anomaly_dir, exist_ok=True)

    synth_healthy_count = 0
    synth_anomaly_count = 0

    # Veena fundamental frequencies (Sa to upper Sa in Carnatic, ~130-520 Hz)
    veena_freqs = [130.8, 146.8, 164.8, 174.6, 196.0, 220.0, 246.9,
                   261.6, 293.7, 329.6, 349.2, 392.0, 440.0, 493.9, 523.3]

    window_dur = 2.0  # 2 seconds

    for i in range(20):
        # Synthetic healthy: veena-like plucked string (harmonics + decay)
        t = np.linspace(0, window_dur, int(TARGET_SR * window_dur), dtype=np.float32)
        f0 = veena_freqs[i % len(veena_freqs)]

        # Plucked string = fundamental + harmonics with exponential decay
        signal = np.zeros_like(t)
        for h in range(1, 8):  # 7 harmonics
            amp = 1.0 / (h ** 1.5)  # Higher harmonics are quieter
            decay = np.exp(-t * (1.0 + h * 0.5))  # Higher harmonics decay faster
            signal += amp * np.sin(2 * np.pi * f0 * h * t) * decay

        # Normalize
        signal = signal / (np.max(np.abs(signal)) + 1e-8) * 0.7
        # Add tiny noise (like real recording)
        signal += np.random.randn(len(signal)).astype(np.float32) * 0.005

        out_path = os.path.join(synth_healthy_dir, f"synth_healthy_{i+1:03d}.wav")
        sf.write(out_path, signal.astype(np.float32), TARGET_SR)
        synth_healthy_count += 1

        # Synthetic anomaly: corrupt the same signal
        atype_name, atype_fn = anomaly_types[i % len(anomaly_types)]
        try:
            corrupted = atype_fn(signal, TARGET_SR)
            out_path = os.path.join(synth_anomaly_dir, f"synth_{atype_name}_{i+1:03d}.wav")
            sf.write(out_path, corrupted.astype(np.float32), TARGET_SR)
            synth_anomaly_count += 1
        except Exception:
            pass

    # Summary
    print(f"\n{'='*55}")
    print(f"DONE! Output:")
    print(f"  {OUTPUT_DIR}/")
    print(f"    Training/healthy:  {len(train_indices)} files")
    print(f"    Testing/healthy:   {len(test_indices)} files")
    print(f"    Testing/anomaly:   {anomaly_count} files")
    print(f"      (detuned: {anomaly_count // 3 + (1 if anomaly_count % 3 > 0 else 0)}, "
          f"buzzing: {anomaly_count // 3 + (1 if anomaly_count % 3 > 1 else 0)}, "
          f"muffled: {anomaly_count // 3})")
    print(f"  synthetic/")
    print(f"    segments_healthy:  {synth_healthy_count} files")
    print(f"    segments_anomaly:  {synth_anomaly_count} files")
    print(f"\nNext step: python 07_yamnet_transfer.py")


if __name__ == "__main__":
    main()
